title: Wireless Communications Conference Deadlines (In working) # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top wireless communications conference deadlines
author: Zhongyuan Zhao

domain: "zhongyuanzhao.com"
baseurl: "/comm-deadlines"

twitter_username: 
twitter_hashtag: 
github_username: zhongyuanzhao
github_repo: comm-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']